# Generated by Django 4.2.16 on 2024-10-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='image_filename',
            field=models.CharField(default='default.png', max_length=255, verbose_name='Имя файла изображения в Minio'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Ссылка на изображение'),
        ),
    ]
