# Generated by Django 4.2.16 on 2024-10-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_ingredient_image_filename_alter_ingredient_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
