# Generated by Django 4.2.16 on 2024-10-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='status',
            field=models.CharField(choices=[('active', 'Действует'), ('deleted', 'Удален')], default='active', max_length=10, verbose_name='Статус'),
        ),
    ]
