# Generated by Django 4.2.16 on 2024-10-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_ingredient_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='image_filename',
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Общая стоимость'),
        ),
    ]
